# Generated by Django 4.2.17 on 2025-01-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pampered_pet_parlor', '0003_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='breed',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
